matrix

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,9 +6,10 @@ on:
       - 'V*.*'
 
 jobs:
-  build:
+  prepare:
     runs-on: ubuntu-latest
-
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
     - name: Check out code
       uses: actions/checkout@v3
@@ -18,43 +19,35 @@ jobs:
       with:
         python-version: '3.x'
 
-    - name: Install PlatformIO
+    - name: Install PlatformIO and dependencies
       run: |
         python -m pip install --upgrade pip
         pip install platformio
 
-    - name: Cache PlatformIO
-      uses: actions/cache@v3
-      with:
-        path: .pio
-        key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
-        restore-keys: |
-          ${{ runner.os }}-pio-
-
     - name: Extract Board Names
-      run: |
-        python extract_boards.py > boards.txt
+      run: python extract_boards.py > boards.txt
+
+    - id: set-matrix
+      run: echo "::set-output name=matrix::$(jq -R -s -c 'split("\n")[:-1]' boards.txt)"
+
+  build:
+    needs: prepare
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        board: ${{fromJson(needs.prepare.outputs.matrix)}}
+    steps:
+    - name: Check out code
+      uses: actions/checkout@v3
 
     - name: Extract Tag Name
       id: get_tag
       run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
 
-    - name: Install GitHub CLI
+    - name: Build for ${{ matrix.board }}
       run: |
-        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
-        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
-        sudo apt update
-        sudo apt install gh
-
-    - name: Authenticate with GitHub CLI
-      run: echo ${{ secrets.GH_PAT }} | gh auth login --with-token
-
-    - name: Build Firmware and Rename .bin files
-      run: |
-        while IFS= read -r board; do
-          pio run -e $board
-          mv .pio/build/$board/firmware.bin .pio/build/Bambulab_Esp32_LEDController_${board}_${{ steps.get_tag.outputs.tag }}.bin
-        done < boards.txt
+        pio run -e ${{ matrix.board }}
+        mv .pio/build/${{ matrix.board }}/firmware.bin .pio/build/Bambulab_Esp32_LEDController_${{ matrix.board }}_${{ steps.get_tag.outputs.tag }}.bin
 
     - name: List renamed .bin files
       run: ls -l .pio/build/
@@ -71,12 +64,10 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GH_PAT }}
 
-    - name: Attach .bin files to Release
+    - name: Attach .bin file to Release
       run: |
-        while IFS= read -r board; do
-          file=.pio/build/Bambulab_Esp32_LEDController_${board}_${{ steps.get_tag.outputs.tag }}.bin
-          echo "Uploading $file to release..."
-          if ! gh release upload ${{ steps.get_tag.outputs.tag }} $file; then
-            echo "Failed to upload $file"
-          fi
-        done < boards.txt
+        file=.pio/build/Bambulab_Esp32_LEDController_${{ matrix.board }}_${{ steps.get_tag.outputs.tag }}.bin
+        echo "Uploading $file to release..."
+        if ! gh release upload ${{ steps.get_tag.outputs.tag }} $file; then
+          echo "Failed to upload $file"
+        fi
