another test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,9 +6,10 @@ on:
       - 'V*.*'
 
 jobs:
-  build:
+  prepare:
     runs-on: ubuntu-latest
-
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
     - name: Check out code
       uses: actions/checkout@v3
@@ -18,81 +19,64 @@ jobs:
       with:
         python-version: '3.x'
 
-    - name: Cache PlatformIO
-      uses: actions/cache@v2
-      with:
-        path: ~/.platformio
-        key: platformio-${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}
-
-    - name: Install PlatformIO
+    - name: Install PlatformIO and dependencies
       run: |
         python -m pip install --upgrade pip
         pip install platformio
 
     - name: Extract Board Names
-      run: |
-        python extract_boards.py > boards.txt
+      run: python extract_boards.py > boards.txt
+
+    - id: set-matrix
+      run: echo "::set-output name=matrix::$(echo $(cat boards.txt))"
+
+  build:
+    needs: prepare
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        board: ${{fromJson(needs.prepare.outputs.matrix)}}
+    steps:
+    - name: Check out code
+      uses: actions/checkout@v3
 
     - name: Extract Tag Name
       id: get_tag
       run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
 
-    - name: Install GitHub CLI
+    - name: Install and setup GitHub CLI
       run: |
         curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
         echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
         sudo apt update
         sudo apt install gh
+        echo ${{ secrets.GH_PAT }} | gh auth login --with-token
 
-    - name: Authenticate with GitHub CLI
-      run: echo ${{ secrets.GH_PAT }} | gh auth login --with-token
-
-    - name: Build Firmware and Rename .bin files
+    - name: Build for ${{ matrix.board }}
       run: |
-        while IFS= read -r board; do
-          pio run -e $board
-          mv .pio/build/$board/firmware.bin .pio/build/Bambulab_Esp32_LEDController_${board}_${{ steps.get_tag.outputs.tag }}.bin
-        done < boards.txt
+        pio run -e ${{ matrix.board }}
+        mkdir -p binaries/${{ matrix.board }}
+        if [[ -f .pio/build/${{ matrix.board }}/firmware.bin ]]; then
+          mv .pio/build/${{ matrix.board }}/firmware.bin binaries/${{ matrix.board }}/Bambulab_Esp32_LEDController_${{ matrix.board }}_${{ steps.get_tag.outputs.tag }}.bin
+          mv .pio/build/${{ matrix.board }}/bootloader.bin binaries/${{ matrix.board }}/
+          mv .pio/build/${{ matrix.board }}/partitions.bin binaries/${{ matrix.board }}/ 
+        else
+          echo "firmware.bin for ${{ matrix.board }} not found!"
+          exit 1
+        fi
 
-    - name: Organize files into folders and push to repository
+    - name: Push binaries to repository
       run: |
         git config user.name "GitHub Actions Bot"
         git config user.email "actions@github.com"
-
-        while IFS= read -r board; do
-          mkdir -p binaries/$board
-          
-          mv .pio/build/$board/firmware.bin binaries/$board/
-          mv .pio/build/$board/bootloader.bin binaries/$board/
-          mv .pio/build/$board/partitions.bin binaries/$board/
-          
-          git add binaries/$board/*
-        done < boards.txt
-
-        git commit -m "Add binaries for boards"
+        git add binaries/${{ matrix.board }}/*
+        git commit -m "Add binaries for ${{ matrix.board }}"
         git push
 
-    - name: List renamed .bin files
-      run: ls -l .pio/build/
-
-    - name: Create Release
-      id: create_release
-      uses: actions/create-release@v1
-      with:
-        tag_name: ${{ github.ref }}
-        release_name: Release ${{ github.ref }}
-        body: Auto-release for ${{ github.ref }}
-        draft: true
-        prerelease: false
-      env:
-        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
-
-    - name: Attach .bin files to Release
+    - name: Attach .bin file to Release
       run: |
-        while IFS= read -r board; do
-          file=.pio/build/Bambulab_Esp32_LEDController_${board}_${{ steps.get_tag.outputs.tag }}.bin
-          echo "Uploading $file to release..."
-          if ! gh release upload ${{ steps.get_tag.outputs.tag }} $file; then
-            echo "Failed to upload $file"
-          fi
-        done < boards.txt
+        file=binaries/${{ matrix.board }}/Bambulab_Esp32_LEDController_${{ matrix.board }}_${{ steps.get_tag.outputs.tag }}.bin
+        echo "Uploading $file to release..."
+        if ! gh release upload ${{ steps.get_tag.outputs.tag }} $file; then
+          echo "Failed to upload $file"
+        fi
